[build]
rustflags = ["-Z", "threads=4",
 # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
]

[unstable]
codegen-backend = true

[profile.'not(any(cfg(target_os = "macos"), cfg(target_arch = "wasm32")))'.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"
